on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
        - cron: "0 0 1 * *" # monthly

name: Quarto Test Build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/boettiger-lab/nasa-tops:latest
      options: --user root --security-opt seccomp=unconfined
    permissions:
      contents: write
    steps:
      - name: Quarto-inside-docker permissions
        run: git config --system --add safe.directory '*'
    
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render
        run: |
             rm -rf _freeze
             quarto render
